### PR TITLE
added basic communication and file sync

### PR DESCRIPTION
**Pull request by pin3da**
At this moment we can use this code in order to communicate the backend and the judgebot. 

Implemented features:
- Download the files just once in the case they are not present previously.
- Multiple bots can join/leave at any time.
- Basic bot reconnection after server failure.

Missing:
-~~Use the real judge and send the real verdict.~~

### CODE REVIEW

**Comment by jhonber** [comment]
This branch is 37 commits behind master : S

**Comment by pin3da** [comment]
updated :+1:

**Comment by jhonber** [comment]
¿Almost ready to merge?

**Comment by pin3da** [comment]
solves #13

**Pull request merged**
